### ISSUE TITLE
Dispatcher implemetation

### ISSUE THREAD

**Issue by mortyccp** [yonekawa/SwiftFlux#14]
In the official flux implementation,  callbacks are not subscribed to particular events. Every payload is dispatched to every registered callback.

In your implementation, callbacks are subscribed to particular event. This makes the waitFor(...) method can't be used to wait for a particular store but to a particular store that listened to a specific event. 

Is there a reason behind this decision?

**Comment by yonekawa** [comment]
You said about this?

``` swift
struct SampleStore: Store {
   init() {
      ActionCreator.dispatcher.register(Action1.self) { (result)
          ...
      }
      ActionCreator.dispatcher.register(Action2.self) { (result)
          ...
      }
   }
}
```

My decision is that we want to dispatch action with explicit types.
An original flux example is here.

``` javascript
AppDispatcher.register(function(action) {
  var text;
  switch(action.actionType) {
    case TodoConstants.ACTION1:
      text = action.text
      break;
    case TodoConstants.ACTION2:
      value = action.value
      break;
  }
}
```

There is two problems.
- We require `switch(action.actionType)` to determine Action treatable
- If we want to know action's data structure such as `action.text`, we have to see Action's source code

SwiftFlux's approach solves these.
We can specify action type to `register` and we can know payload type with Generics.
Then, swift compiler supports development with code completion and type check.

> This makes the waitFor(...) method can't be used to wait for a particular store but to a particular store that listened to a specific event.

Hm, I think you can use `waitFor` to each events with `Array`.

``` swift
struct SampleStore: Store {
   var dispatchTokens = [String]()

   init() {
      dispatchTokens.append(
        ActionCreator.dispatcher.register(Action1.self) { (result)
            ...
        }
      )
      dispatchTokens.append(
        ActionCreator.dispatcher.register(Action2.self) { (result)
            ...
        }
      )
   }
}

struct OtherStore: Store {
  init () {
    ActionCreator.dispatcher.register(Action1.self) { (result)
        ActionCreator.dispatcher.waitFor(sampleStore.dispatchTokens)
    }
  }
}
```

Maybe, we need to implement this pattern into `StoreBase`.
Any problem?

**Comment by mortyccp** [comment]
Thank you for clear explanation. 
Having an array of tokens in StoreBase seem to be a feasible alternative to provide the same `waitFor(...)` functionality as the official implementation.
It is good to have it implemented in the StoreBase.

**Comment by yonekawa** [comment]
Okay, I will implement this pattern into next release.
Thank you for your feedback!
